# Calculating Eigen values and Eigen Vectors

### Eigenvalues and Eigenvectors of a $2 \times 2$ Matrix

Consider a matrix

$$
A =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$
An eigenvector $\mathbf{v}$ and its corresponding eigenvalue $\lambda$ satisfy

$$
A\mathbf{v} = \lambda\mathbf{v}
$$
#### 1. Finding the Eigenvalues
we move everything to one side:
$$
\det(A-\lambda I)=0
$$
For $$
A =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

we have

$$
A-\lambda I =
\begin{bmatrix}
a-\lambda & b \\
c & d-\lambda
\end{bmatrix}
$$
$$
(a-\lambda)(d-\lambda)-bc=0
$$
$$
ad-a\lambda-d\lambda+\lambda^2-bc=0
$$
$$
\lambda^2-(a+d)\lambda+(ad-bc)=0
$$

The trace of $A$ is $$\operatorname{tr}(A)=a+d $$ and the determinant is $$ \det(A)=ad-bc $$

Therefore, the characteristic equation can be written as

$$
\lambda^2-\operatorname{tr}(A)\lambda+\det(A)=0
$$
#### 2. Discriminant
The discriminant is$$ \Delta = \operatorname{tr}(A)^2-4\det(A)$$
The discriminant determines the type of eigenvalues:
$$
\Delta > 0
\quad\Rightarrow\quad
\text{two different real eigenvalues}
$$
$$
\Delta = 0
\quad\Rightarrow\quad
\text{repeated real eigenvalue}
$$
$$
\Delta < 0
\quad\Rightarrow\quad
\text{complex eigenvalues}
$$


#### 3. Eigenvalue Formula

Using the quadratic formula,

$$
\lambda_{1,2}
=
\frac{
\operatorname{tr}(A)
\pm
\sqrt{
\operatorname{tr}(A)^2-4\det(A)
}
}{2}
$$

#### 4. Finding the Eigenvectors

Once an eigenvalue $\lambda$ is known, its eigenvector is found by solving

$$
(A-\lambda I)\mathbf{v}=0
$$

where

$$
\mathbf{v}=
\begin{bmatrix}
x\\
y
\end{bmatrix}
$$

For a general $2\times2$ matrix,

$$
\begin{bmatrix}
a-\lambda&b\\
c&d-\lambda
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
0\\
0
\end{bmatrix}
$$

This produces the equations

$$
(a-\lambda)x+by=0
$$

and

$$
cx+(d-\lambda)y=0
$$
#### 5. Normalizing the Eigenvectors

The code normalizes each eigenvector so that its magnitude is $1$.


In [4]:
import numpy as np

In [8]:
def eigenvalue_2x2(A):
    a,b = A[0]
    c,d = A[1]
    trace = a + d
    determinant = a*d - b*c

    discriminant = np.pow(trace,2) - 4* determinant

    if discriminant < 0:
        print("Roots are imaginary")
    ## Need to add complex number code
        return 
    sqr_root_disc = np.sqrt(discriminant)

    # lambda^2 - trace(A) * lambda + det(A) = 0
    pos_root =(trace + sqr_root_disc) / 2
    neg_root =(trace - sqr_root_disc) / 2

    return [pos_root, neg_root]

def eigenvector_2x2(A, eigenvalue):
    a, b = A[0]
    c, d = A[1]

    '''
    [a-lambda     b  ] *[x] = 0
    [c       d-lambda]  [y]
    
    '''
    # (a - lambda)x + by = 0
    # Let's choose x = 1
    x = 1

    if b != 0:
        y = -(a - eigenvalue) * x / b
    elif c != 0:
        # If first equation doesn't help,
        # use cx + (d-lambda)y = 0
        y = 1
        x = -(d - eigenvalue) * y / c
    else:
        # b = 0 and c = 0
        # [a,0] [0,d] = [a-lambda , 0] [ 0, d-lambda]
        # det = a-lambda * d-lambda = 0
        # lambda = a or d, so A-lambda* I  = [0,0][0,d-a] or [a-d,0][0,0]
         if a == eigenvalue:
            # [0,0][0,d-a] * [x][y] = 0
            # d-a * y = 0
             # y = 0
            x = 1
            y = 0
         else:
            x = 0
            y = 1

    mag = np.sqrt(np.pow(x,2) + np.pow(y,2))
    return [x/mag, y/mag]

In [9]:
A = np.array([[2,1],[2,3]])
eigen_values = eigenvalue_2x2(A)
print("Eigen Values:", eigen_values)
print()
for val in eigen_values:
    eigen_vector = eigenvector_2x2(A,val)
    AXv= A @ eigen_vector
    lambdaXv = []
    for ele in eigen_vector:
        lambdaXv.append(val*ele)

    print("A X v:",AXv)
    print("lambda X v:",lambdaXv)
    print("is A X v = lambda X v ?",np.allclose(AXv, lambdaXv))
    print()

Eigen Values: [np.float64(4.0), np.float64(1.0)]

A X v: [1.78885438 3.57770876]
lambda X v: [np.float64(1.7888543819998317), np.float64(3.5777087639996634)]
is A X v = lambda X v ? True

A X v: [ 0.70710678 -0.70710678]
lambda X v: [np.float64(0.7071067811865475), np.float64(-0.7071067811865475)]
is A X v = lambda X v ? True



#### For 3 x 3 Matrix: 
A → Find det(A−λI)=0→ characteristic polynomial equation→ Find λ(Eigen Values) → Apply eigen values in (A−λI)v=0→row reduction→ Find eigen vectors -> v

In computers, Eigen values are calculated using QR Algorithm. 
- $${A = QR}$$ A decomposed to Q and R. Q is a orthogonal matrix. Q_T = Q-1
- $${RQ=A_1}$$ But when we reverse them, we get a different matrix that has the same eigenvalues.
- $${A_1 = Q_1R_1}$$
- $${R_1Q_1 = A_2}$$
- Do this enough times, to get A as an upper triangular matrix, which has eigen values in the diagonals.

In [18]:
#### Code version of it
def eigenvalues_3x3(A, max_iterations=1000):

    A = A.astype(float)

    for iteration in range(max_iterations):

        Q, R = np.linalg.qr(A)
        A = R @ Q

        lower = np.tril(A, -1) # Shifts the diagonal one below and make everything 0 above

        if np.all(np.abs(lower) < 1e-10):  # all elements are approximately 0 
            print("Iterations:", iteration + 1)
            return np.diag(A)

    print("Did not converge")
    return np.diag(A)

def row_reduce(M):
    rows = len(M)
    cols = len(M[0])   
    rank=0
    
    for col in range(cols):
        pivot_row=None
        
        for row in range(rank,rows):
            if M[row][col] != 0:
                pivot_row = row
                break
        if pivot_row is None:
            continue
        M[rank], M[pivot_row] = M[pivot_row], M[rank]
        
        # Eliminate entries below the pivot
        pivot = M[rank][col]
        for row in range(rank+1,rows):
            factor = M[row][col]/ pivot
            for j in range(col,cols):
                M[row][j] = M[row][j] - factor * M[rank][j]
        rank+=1
    print("Matrix after row reduction:\n",M)

def null_vectors(M):
    rows = len(M)
    cols = len(M[0])
    pivot_col = []
    for row in range(rows):
        for col in range(cols):
            if M[row][col] > 0:
                pivot_col.append(col)
                break
    free_cols = []
    for col in range(cols):
        if col not in pivot_cols:
            free_cols.append(col)

    if not free_cols:
        raise ValueError("Only the zero vector exists.")

    free_col = free_cols[0]
    v = np.zeros(cols)
    v[free_col] = 1

def eigenvectors_3x3(A,eigenvalue):
    rows = len(A)
    M = A.astype(float).copy()

    for i in range(rows):
        M[i][i]-=eigenvalue
        
    row_reduce(M)
    null_vectors(M)
      
    
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
eign = eigenvalues_3x3(A)
for value in eign:
    eigenvectors_3x3(A,value)

Iterations: 10
Matrix after row reduction:
 [[-1.51168440e+01  2.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -1.05876330e+01  6.79381649e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.96918054e-11]]
Matrix after row reduction:
 [[2.11684397e+00 2.00000000e+00 3.00000000e+00]
 [0.00000000e+00 2.33763298e+00 3.31183511e-01]
 [8.88178420e-16 0.00000000e+00 8.89584517e-11]]
Matrix after row reduction:
 [[ 1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -3.00000000e+00 -6.00000000e+00]
 [ 0.00000000e+00 -8.88178420e-16 -1.77635684e-15]]
